// Generated by `npm run images:resize` (scripts/generate-responsive-images.mjs).
// Native source images are 1672px wide — requests at or above that fall back
// to the original file instead of an upscaled copy.
const GENERATED_WIDTHS = [640, 960, 1280] as const;

const responsive = (base: string) => (w: number) => {
  const width = GENERATED_WIDTHS.find((candidate) => candidate >= w);
  return width ? `/img/${base}-${width}.webp` : `/img/${base}.webp`;
};

export const images = {
  heroExterior: responsive('hero'),
  casaHorizonte: responsive('casa-horizonte'),
  casaAlerce: responsive('casa-alerce'),
  pabellonCostanera: responsive('pabellon-costanera'),
  casaPiedra: responsive('casa-piedra'),
  studioInterior: responsive('studio-interior'),
  featuredInterior: responsive('featured-interior'),
  contactInterior: responsive('contact-interior'),
  approachA: responsive('approach-a'),
  approachB: responsive('approach-b'),
  approachC: responsive('approach-c'),
  proyectado: responsive('proyectado'),
};
